[package_type.language_env]
language_env = "java"
is_oracle=true
jdk_version="17.0"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[package_type.language_env.gradle]
gradle_version="8.7"
gradle_binary_checksum="544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d"

[build_env]
codename = "bookworm"
arch = "amd64"
pkg_builder_version = "0.1"
debcrafter_version = "latest"

[verify]
package_hash=""
