[package_fields]
spec_file = "hello-world.sss"
package_name = "hello-world"
version_number = "1.0.0"
revision_number = "1"
tarball_url = "hello-world-1.0.0.tar.gz"
git_source = ""
# virtual | git | default
package_type = "default"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-1.0.0.tar.gz"
tarball_hash = "9838986aeb5fbf1e24fc20da08772c2264b5e0ace8a09b423c39cdc8774b0c04"

[package_type.language_env]
language_env = "java"
is_oracle=true
jdk_version="17.0"
jdk_binary_url="https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[package_type.language_env.gradle]
gradle_version="8.7"
gradle_binary_url="https://github.com/gradle/gradle-distributions/releases/download/v8.7.0/gradle-8.7-bin.zip"
gradle_binary_checksum="544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d"

[build_env]
codename = "bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version = "0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian = false
run_piuparts = false
run_autopkgtest = false
# package directory
workdir = "~/.pkg-builder/packages"

[cli_options]
# not used
is_ci = false
log = "info"
log_to = "file"
reuse_previous_build = false

[verify]
# if tarball_url is specified
tarball_hash = ""
# if git_source is specified and package_is_git
git_commit = ""
# output hash
bin_bash = ""