[package_type]
tarball_hash = "c361ad7853f4eb1e272eb10fe70ac8a5fd40677da5d23e205e1808f2c6f3bed7"

[package_type.language_env]
language_env = "java"
is_oracle=true
jdk_version="17.0"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[build_env]
codename = "bookworm"
arch = "amd64"
pkg_builder_version = "0.1"
debcrafter_version = "latest"


[verify]
package_hash=""
