[package_type.language_env]
language_env = "javascript"
node_version = "20.12.2"
node_binary_checksum = "f8f9b6877778ed2d5f920a5bd853f0f8a8be1c42f6d448c763a95625cbbb4b0d"
yarn_version = "1.22.19"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.1"
debcrafter_version = "latest"

[verify]
package_hash=""
git_commit=""
bin_bash=""