[verify]
package_hash=[
    { hash="4f2be308e80353ce533122b81810ec6f20b26a1a", name= "hello-world-javascript_1.0.0-1.dsc"},
    { hash="161b7ac1a3dea76b1f98b10f0ae57ea601b9e642", name= "hello-world-javascript_1.0.0.orig.tar.gz"},
    { hash="f4465e5c648cec0d64daedff3a652df9e3735ec3", name= "hello-world-javascript_1.0.0-1.debian.tar.xz"},
    { hash="b3f6edaa64dfbf0dc11672ac7b8f42f0f14731d2", name= "hello-world-javascript_1.0.0-1_amd64.deb"},
]