[package_type]
tarball_hash = "f263892f5ed6cbcd82f31d60058eed359686d7e745c3da97fea917ee2f44867c4db9bd374f224e89e6efc7ffad4eadb244eefe7c95d25983f8a5a4086dadb78d"

[package_type.language_env]
language_env = "dotnet"
dotnet_version = "8.0"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.1"
debcrafter_version = "latest"

[verify]
package_hash=""
