[package_type.language_env]
language_env = "java-gradle"
is_oracle=true
jdk_version="17.0"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[package_type.language_env.gradle]
gradle_version="8.7"
gradle_binary_checksum="544c35d6bd849ae8a5ed0bcea39ba677dc40f49df7d1835561582da2009b961d"

[build_env]
codename = "bookworm"
arch = "amd64"
pkg_builder_version = "0.1"
debcrafter_version = "latest"

[verify]
package_hash=[
    { hash="0dce1ae2d924c5297bddf787dea68f3e1cfd63e6", name= "hello-world-java-gradle_1.0.0-1.dsc"},
    { hash="eef991395fabb27016cc1a2e37cbaa04fd869de8", name= "hello-world-java-gradle_1.0.0.orig.tar.gz"},
    { hash="a60103c828996cd025a5f7ca56d84377204ba9b8", name= "hello-world-java-gradle_1.0.0-1.debian.tar.xz"},
    { hash="10372f1f48d99dd8b67dc31c2b8a086fe4c1e3f8", name= "hello-world-java-gradle_1.0.0-1_amd64.deb"},
]