[package_type]
tarball_hash = "c93bdd829eca65af1e303d4a0b31cde0c3d3c2003fa1ca985393c412264b42c3b30c7893eb1d49ea654ca4f68269c30b3cca3db66d6b112f2be14f54c3d0edff"

[package_type.language_env]
language_env = "c"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.1"
debcrafter_version = "latest"

[verify]
package_hash=""
