[package_fields]
spec_file = "hello-world.sss"
package_name = "hello-world"
version_number = "1.0.0"
revision_number = "1"
homepage="https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-1.0.0.tar.gz"
tarball_hash = "c93bdd829eca65af1e303d4a0b31cde0c3d3c2003fa1ca985393c412264b42c3b30c7893eb1d49ea654ca4f68269c30b3cca3db66d6b112f2be14f54c3d0edff"

[package_type.language_env]
language_env = "c"

[build_env]
codename="bookworm"
arch = "amd64"
# TODO not used yet
pkg_builder_version="0.1"
# TODO not used yet
debcrafter_version = "latest"
run_lintian=true
run_piuparts=true
run_autopkgtest=false
# package directory
workdir="~/.pkg-builder/packages"

[cli_options]
# not used
is_ci=false
log="info"
log_to="file"
reuse_previous_build=false

[verify]
# if tarball_url is specified
tarball_hash=""
# if git_source is specified and package_is_git
git_commit=""
# output hash
bin_bash=""