[package_type.language_env]
language_env = "javascript"
node_version = "20.12.2"
node_binary_checksum = "f8f9b6877778ed2d5f920a5bd853f0f8a8be1c42f6d448c763a95625cbbb4b0d"
yarn_version = "1.22.19"

[build_env]
codename="bookworm"
arch = "amd64"
pkg_builder_version="0.1"
debcrafter_version = "latest"

[verify]
package_hash=[
    { hash="bc4ba6701535de8c2aa989681099e726f3b77cd5", name= "hello-world-javascript_1.0.0-1.dsc"},
    { hash="161b7ac1a3dea76b1f98b10f0ae57ea601b9e642", name= "hello-world-javascript_1.0.0.orig.tar.gz"},
    { hash="e3aae4e1030935bae065d68aae4c14774227908c", name= "hello-world-javascript_1.0.0-1.debian.tar.xz"},
    { hash="f129edc9543cc4566daa067c24b1923b166fc188", name= "hello-world-javascript_1.0.0-1_amd64.deb"},
]