name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  sbuild:
    runs-on: ubuntu-latest
    steps:  
      - name: Cache sbuild
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /usr/bin/sbuild
          key: sbuild-${{ runner.os }}-${{ hashFiles('**/apt.txt') }}

      - if: ${{ sbuild-${{ runner.os }}-${{ hashFiles('**/apt.txt') }} != 'true' }}
        name: Check if sbuild is installed
        run: dpkg -s sbuild && exit 1 || exit 0
        id: check-installed
        continue-on-error: true
  
      - name: Checkout sbuild Repository
        uses: actions/checkout@v2
        with:
          repository: eth-pkg/sbuild
          ref: main

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dh-python dh-sequence-python3 libyaml-tiny-perl python3-all

      - name: Build Sbuild
        run: |
          cd sbuild
          dpkg-buildpackage -us -uc

      - name: Install Sbuild
        run: |
          sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb
  test:
    runs-on: ubuntu-latest
    needs: sbuild

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
