name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sbuild setup
        run: |
          sudo apt-get update
          # Note this is an older version of sbuild, no need to patch it, yet
          sudo apt install -y debhelper schroot ubuntu-dev-tools piuparts
          sudo apt-get -y install pkg-config libssl-dev uidmap
          sudo apt-get install -y libfilesys-df-perl libmime-lite-perl
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6-1/sbuild_0.85.6_all.deb
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6-1/libsbuild-perl_0.85.6_all.deb
          sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb || true
      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose

  bookworm_packaging:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language:
          - virtual
          - c
          - dotnet
          - go
          - java
          - javascript
          - nim
          - rust
          - typescript
          - gradle-java
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sbuild setup
        run: |
          sudo apt-get update
          # Note this is an older version of sbuild, no need to patch it, yet
          sudo apt install -y debhelper schroot ubuntu-dev-tools piuparts autopkgtest vmdb2 qemu-system-x86
          sudo apt-get install -y pkg-config libssl-dev uidmap
          sudo apt-get install -y libfilesys-df-perl libmime-lite-perl
          # change this into actually built version and cache it
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6-1/sbuild_0.85.6_all.deb
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6-1/libsbuild-perl_0.85.6_all.deb
          sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb || true

      - name: Build
        run: cargo build --verbose

      - name: package
        run: |
          pkg-builder package --run-piuparts false --run-autopkgtests false --run-lintian false examples/bookworm/${{maxtrix.language}}/pkg-builder.toml 


      - name: piuparts
        run: |
          # installing debian-archive-keyring fails on ubuntu LTS, not sure why, but it says it is already installed
          # sudo apt-get install -y debian-archive-keyring
          ${HOME}/.local/bin/pkg-builder piuparts ${{maxtrix.language}}/pkg-builder.toml

      - name: autopkgtests
        run: |
          sudo cp -R ${HOME}/.pkg-builder /root
          sudo ${HOME}/.local/bin/pkg-builder piuparts examples/bookworm/${{maxtrix.language}}/pkg-builder.toml

      - name: verify
        run: |
          ${HOME}/.local/bin/pkg-builder verify --config-file examples/bookworm/${{maxtrix.language}}/pkg-builder.toml  --verify-config-file examples/bookworm/${{maxtrix.language}}/pkg-builder-verify.toml  --no-package true 
  

