name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sbuild setup
        run: |
          sudo apt-get update
          # Note this is an older version of sbuild, no need to patch it, yet
          sudo apt install debhelper sbuild schroot ubuntu-dev-tools
          sudo apt-get install pkg-config libssl-dev uidmap

      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose

  bookworm_packaging:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language:
#          - virtual
#          - dotnet
          - go
#          - java
#          - javascript
#          - nim
#          - rust
#          - typescript
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Sbuild setup
          run: |
            sudo apt-get update
            # Note this is an older version of sbuild, no need to patch it, yet
            sudo apt install debhelper sbuild schroot ubuntu-dev-tools
            sudo apt-get install pkg-config libssl-dev uidmap
        - name: .sbuildrc
          run: |
            pwd
            cp src/overrides/.sbuildrc-github /home/runner/.sbuildrc
            echo "/home/runner/.sbuildrc" >> $GITHUB_PATH

        - name: Build
          run: cargo build --verbose  

        - name: Test ${{ matrix.language }} packaging
          run: cargo test --verbose --test sbuild tests::test_build_${{ matrix.language }}_package_in_sbuild_env

