name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sbuild setup
        run: |
          sudo apt-get update
          # Note this is an older version of sbuild, no need to patch it, yet
          sudo apt install -y debhelper schroot ubuntu-dev-tools piuparts
          sudo apt-get -y install pkg-config libssl-dev uidmap
          sudo apt-get install -y libfilesys-df-perl libmime-lite-perl
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6/sbuild_0.85.6_all.deb
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6/libsbuild-perl_0.85.6_all.deb
          sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb || true
      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose

  bookworm_packaging:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language:
          - virtual
          - dotnet
          - go
          - java
          - javascript
          - nim
          - rust
          - typescript
          - gradle_java
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sbuild setup
        run: |
          sudo apt-get update
          # Note this is an older version of sbuild, no need to patch it, yet
          sudo apt install -y debhelper schroot ubuntu-dev-tools piuparts
          sudo apt-get install -y pkg-config libssl-dev uidmap
          sudo apt-get install -y libfilesys-df-perl libmime-lite-perl
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6/sbuild_0.85.6_all.deb
          wget https://github.com/eth-pkg/sbuild-ubuntu/releases/download/0.85-6/libsbuild-perl_0.85.6_all.deb
          sudo dpkg -i sbuild_0.85.6_all.deb libsbuild-perl_0.85.6_all.deb || true

      - name: Build
        run: cargo build --verbose

      - name: Test ${{ matrix.language }} packaging
        run: |
          cargo test --verbose --test sbuild tests::test_build_${{ matrix.language }}_package_in_sbuild_env

      - name: Piuparts on ${{ matrix.language }}
        # TODO seperate piuparts and autopkgtest into their own command, as not to run the packaging as root
        # though as it runs under chroot it won't affect things
        run: |
          which cargo
          sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo sh -s -- -y
          sudo /home/runner/.cargo/bin/cargo test --verbose --test sbuild tests::test_build_${{ matrix.language }}_package_in_sbuild_env_piuparts -- ignored

